<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class JugadoresSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('jugadores')->insert([
            ["rut"=>"10932457-4","nombre"=>"Bruce","apellido"=>"Challinor","numero_camiseta"=>37,"posicion"=>"Delantero","equipo_id"=>7,"created_at"=>Carbon::now()],
            ["rut"=>"15248489-1","nombre"=>"Law","apellido"=>"Teape","numero_camiseta"=>35,"posicion"=>"Defensa","equipo_id"=>1,"created_at"=>Carbon::now()],
            ["rut"=>"14598417-4","nombre"=>"Irwin","apellido"=>"Gentil","numero_camiseta"=>26,"posicion"=>"Delantero","equipo_id"=>7,"created_at"=>Carbon::now()],
            ["rut"=>"23353840-9","nombre"=>"Killy","apellido"=>"Minker","numero_camiseta"=>24,"posicion"=>"Volante","equipo_id"=>6,"created_at"=>Carbon::now()],
            ["rut"=>"21721084-3","nombre"=>"Cris","apellido"=>"Mathevon","numero_camiseta"=>12,"posicion"=>"Arquero","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"14174620-0","nombre"=>"Albert","apellido"=>"Vayro","numero_camiseta"=>6,"posicion"=>"Arquero","equipo_id"=>7,"created_at"=>Carbon::now()],
            ["rut"=>"27015797-3","nombre"=>"Aleksandr","apellido"=>"Orme","numero_camiseta"=>16,"posicion"=>"Delantero","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"13253741-5","nombre"=>"Rip","apellido"=>"Jaquet","numero_camiseta"=>10,"posicion"=>"Volante","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"23039509-4","nombre"=>"Neils","apellido"=>"Plitz","numero_camiseta"=>17,"posicion"=>"Delantero","equipo_id"=>4,"created_at"=>Carbon::now()],
            ["rut"=>"15677532-3","nombre"=>"Scot","apellido"=>"Leader","numero_camiseta"=>28,"posicion"=>"Volante","equipo_id"=>7,"created_at"=>Carbon::now()],
            ["rut"=>"21369273-0","nombre"=>"Karel","apellido"=>"Haycock","numero_camiseta"=>18,"posicion"=>"Volante","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"18052851-9","nombre"=>"Dene","apellido"=>"Theakston","numero_camiseta"=>12,"posicion"=>"Arquero","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"18999548-5","nombre"=>"Harlan","apellido"=>"Poundford","numero_camiseta"=>29,"posicion"=>"Delantero","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"28399558-6","nombre"=>"Phip","apellido"=>"Wathen","numero_camiseta"=>18,"posicion"=>"Defensa","equipo_id"=>2,"created_at"=>Carbon::now()],
            ["rut"=>"14033507-0","nombre"=>"Gradeigh","apellido"=>"Lauritsen","numero_camiseta"=>25,"posicion"=>"Arquero","equipo_id"=>4,"created_at"=>Carbon::now()],
            ["rut"=>"19417988-5","nombre"=>"Guthrie","apellido"=>"Gething","numero_camiseta"=>18,"posicion"=>"Defensa","equipo_id"=>2,"created_at"=>Carbon::now()],
            ["rut"=>"16926431-8","nombre"=>"Stevie","apellido"=>"Dillestone","numero_camiseta"=>2,"posicion"=>"Delantero","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"15490601-5","nombre"=>"Codi","apellido"=>"Kneath","numero_camiseta"=>19,"posicion"=>"Delantero","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"18323121-2","nombre"=>"Cristiano","apellido"=>"Deguara","numero_camiseta"=>39,"posicion"=>"Volante","equipo_id"=>1,"created_at"=>Carbon::now()],
            ["rut"=>"21101251-8","nombre"=>"Devlen","apellido"=>"Ipplett","numero_camiseta"=>17,"posicion"=>"Volante","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"24795111-1","nombre"=>"Orrin","apellido"=>"Stubs","numero_camiseta"=>29,"posicion"=>"Arquero","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"20606861-4","nombre"=>"Alic","apellido"=>"McOmish","numero_camiseta"=>32,"posicion"=>"Delantero","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"22601327-0","nombre"=>"Mort","apellido"=>"Gentil","numero_camiseta"=>33,"posicion"=>"Defensa","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"22986009-4","nombre"=>"Geoff","apellido"=>"Mounce","numero_camiseta"=>11,"posicion"=>"Volante","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"26711024-8","nombre"=>"Jarrod","apellido"=>"Lightbowne","numero_camiseta"=>10,"posicion"=>"Defensa","equipo_id"=>1,"created_at"=>Carbon::now()],
            ["rut"=>"20185942-4","nombre"=>"Sherman","apellido"=>"Twiggs","numero_camiseta"=>19,"posicion"=>"Arquero","equipo_id"=>6,"created_at"=>Carbon::now()],
            ["rut"=>"16044371-3","nombre"=>"Torr","apellido"=>"Callan","numero_camiseta"=>1,"posicion"=>"Arquero","equipo_id"=>6,"created_at"=>Carbon::now()],
            ["rut"=>"27916444-2","nombre"=>"Wallache","apellido"=>"Larway","numero_camiseta"=>30,"posicion"=>"Arquero","equipo_id"=>2,"created_at"=>Carbon::now()],
            ["rut"=>"16749366-6","nombre"=>"Durand","apellido"=>"Romayn","numero_camiseta"=>11,"posicion"=>"Volante","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"21172341-2","nombre"=>"Sonny","apellido"=>"Obee","numero_camiseta"=>34,"posicion"=>"Volante","equipo_id"=>6,"created_at"=>Carbon::now()],
            ["rut"=>"23464041-6","nombre"=>"Nollie","apellido"=>"Ollin","numero_camiseta"=>7,"posicion"=>"Delantero","equipo_id"=>6,"created_at"=>Carbon::now()],
            ["rut"=>"13913276-4","nombre"=>"Cristobal","apellido"=>"Kondrat","numero_camiseta"=>6,"posicion"=>"Defensa","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"25256075-4","nombre"=>"Godfrey","apellido"=>"Ilott","numero_camiseta"=>40,"posicion"=>"Arquero","equipo_id"=>2,"created_at"=>Carbon::now()],
            ["rut"=>"10400458-7","nombre"=>"Aloysius","apellido"=>"Reaper","numero_camiseta"=>5,"posicion"=>"Defensa","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"20925736-5","nombre"=>"Christophorus","apellido"=>"Bidder","numero_camiseta"=>32,"posicion"=>"Volante","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"25500900-2","nombre"=>"Irving","apellido"=>"O'Hogertie","numero_camiseta"=>29,"posicion"=>"Delantero","equipo_id"=>4,"created_at"=>Carbon::now()],
            ["rut"=>"23799012-7","nombre"=>"Ave","apellido"=>"Bleasdille","numero_camiseta"=>32,"posicion"=>"Defensa","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"18133982-9","nombre"=>"Waylon","apellido"=>"Pinilla","numero_camiseta"=>18,"posicion"=>"Volante","equipo_id"=>2,"created_at"=>Carbon::now()],
            ["rut"=>"23299494-9","nombre"=>"Job","apellido"=>"Taggerty","numero_camiseta"=>18,"posicion"=>"Arquero","equipo_id"=>6,"created_at"=>Carbon::now()],
            ["rut"=>"16075734-5","nombre"=>"Ky","apellido"=>"Fetter","numero_camiseta"=>22,"posicion"=>"Volante","equipo_id"=>4,"created_at"=>Carbon::now()],
            ["rut"=>"17711214-4","nombre"=>"Bevan","apellido"=>"Nuzzti","numero_camiseta"=>7,"posicion"=>"Arquero","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"27443539-2","nombre"=>"Cosmo","apellido"=>"Winterflood","numero_camiseta"=>2,"posicion"=>"Arquero","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"21742004-3","nombre"=>"Camey","apellido"=>"Forcer","numero_camiseta"=>7,"posicion"=>"Arquero","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"11875616-2","nombre"=>"Burgess","apellido"=>"Berthod","numero_camiseta"=>2,"posicion"=>"Arquero","equipo_id"=>7,"created_at"=>Carbon::now()],
            ["rut"=>"21257060-5","nombre"=>"Mattheus","apellido"=>"Drinkeld","numero_camiseta"=>4,"posicion"=>"Volante","equipo_id"=>2,"created_at"=>Carbon::now()],
            ["rut"=>"27692461-8","nombre"=>"Merv","apellido"=>"Streeter","numero_camiseta"=>16,"posicion"=>"Arquero","equipo_id"=>4,"created_at"=>Carbon::now()],
            ["rut"=>"15483620-4","nombre"=>"Vlad","apellido"=>"Kenwyn","numero_camiseta"=>9,"posicion"=>"Arquero","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"11001615-5","nombre"=>"Amble","apellido"=>"Glendenning","numero_camiseta"=>17,"posicion"=>"Delantero","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"20705569-7","nombre"=>"Alexandro","apellido"=>"Petkov","numero_camiseta"=>14,"posicion"=>"Volante","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"19089412-2","nombre"=>"Huntington","apellido"=>"Gonzales","numero_camiseta"=>10,"posicion"=>"Delantero","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"10618768-5","nombre"=>"Chrotoem","apellido"=>"Ehlerding","numero_camiseta"=>40,"posicion"=>"Arquero","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"12501301-4","nombre"=>"Tyler","apellido"=>"Jumel","numero_camiseta"=>33,"posicion"=>"Delantero","equipo_id"=>6,"created_at"=>Carbon::now()],
            ["rut"=>"28770213-5","nombre"=>"Matty","apellido"=>"See","numero_camiseta"=>15,"posicion"=>"Arquero","equipo_id"=>7,"created_at"=>Carbon::now()],
            ["rut"=>"14799570-1","nombre"=>"Der","apellido"=>"Marczyk","numero_camiseta"=>12,"posicion"=>"Volante","equipo_id"=>2,"created_at"=>Carbon::now()],
            ["rut"=>"13701626-3","nombre"=>"Chris","apellido"=>"Russel","numero_camiseta"=>23,"posicion"=>"Volante","equipo_id"=>4,"created_at"=>Carbon::now()],
            ["rut"=>"26894017-7","nombre"=>"Lorens","apellido"=>"Blazewicz","numero_camiseta"=>12,"posicion"=>"Delantero","equipo_id"=>2,"created_at"=>Carbon::now()],
            ["rut"=>"21621625-9","nombre"=>"Reilly","apellido"=>"Gheraldi","numero_camiseta"=>13,"posicion"=>"Volante","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"26372857-3","nombre"=>"Donny","apellido"=>"Plummer","numero_camiseta"=>33,"posicion"=>"Arquero","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"17911948-8","nombre"=>"Chancey","apellido"=>"Enderle","numero_camiseta"=>25,"posicion"=>"Arquero","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"20979663-7","nombre"=>"Marco","apellido"=>"Sara","numero_camiseta"=>40,"posicion"=>"Arquero","equipo_id"=>1,"created_at"=>Carbon::now()],
            ["rut"=>"13310527-1","nombre"=>"Whittaker","apellido"=>"Geraudel","numero_camiseta"=>30,"posicion"=>"Volante","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"25682990-2","nombre"=>"Dewey","apellido"=>"Annes","numero_camiseta"=>10,"posicion"=>"Defensa","equipo_id"=>4,"created_at"=>Carbon::now()],
            ["rut"=>"16085307-7","nombre"=>"Clevey","apellido"=>"Mollatt","numero_camiseta"=>28,"posicion"=>"Volante","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"12716402-1","nombre"=>"Onfroi","apellido"=>"Larmet","numero_camiseta"=>6,"posicion"=>"Defensa","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"19247953-9","nombre"=>"Fredek","apellido"=>"Milazzo","numero_camiseta"=>19,"posicion"=>"Defensa","equipo_id"=>1,"created_at"=>Carbon::now()],
            ["rut"=>"21737848-4","nombre"=>"Lambert","apellido"=>"Finnigan","numero_camiseta"=>19,"posicion"=>"Delantero","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"29734001-6","nombre"=>"Perry","apellido"=>"Twitchett","numero_camiseta"=>11,"posicion"=>"Defensa","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"12611517-5","nombre"=>"Holly","apellido"=>"McKiernan","numero_camiseta"=>24,"posicion"=>"Defensa","equipo_id"=>2,"created_at"=>Carbon::now()],
            ["rut"=>"23687383-5","nombre"=>"Anselm","apellido"=>"Pinar","numero_camiseta"=>23,"posicion"=>"Arquero","equipo_id"=>1,"created_at"=>Carbon::now()],
            ["rut"=>"13628975-6","nombre"=>"Torin","apellido"=>"Soda","numero_camiseta"=>39,"posicion"=>"Volante","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"25473345-8","nombre"=>"Alexio","apellido"=>"Tresvina","numero_camiseta"=>2,"posicion"=>"Delantero","equipo_id"=>1,"created_at"=>Carbon::now()],
            ["rut"=>"21328144-9","nombre"=>"Amby","apellido"=>"Garbar","numero_camiseta"=>7,"posicion"=>"Delantero","equipo_id"=>6,"created_at"=>Carbon::now()],
            ["rut"=>"10482891-8","nombre"=>"Ryley","apellido"=>"Matthewson","numero_camiseta"=>10,"posicion"=>"Arquero","equipo_id"=>7,"created_at"=>Carbon::now()],
            ["rut"=>"29203813-8","nombre"=>"Richy","apellido"=>"Brandt","numero_camiseta"=>1,"posicion"=>"Delantero","equipo_id"=>2,"created_at"=>Carbon::now()],
            ["rut"=>"24322138-2","nombre"=>"Alon","apellido"=>"De Benedictis","numero_camiseta"=>8,"posicion"=>"Defensa","equipo_id"=>6,"created_at"=>Carbon::now()],
            ["rut"=>"13783944-9","nombre"=>"Irvine","apellido"=>"Lincke","numero_camiseta"=>29,"posicion"=>"Defensa","equipo_id"=>4,"created_at"=>Carbon::now()],
            ["rut"=>"27523904-0","nombre"=>"Jasen","apellido"=>"Dench","numero_camiseta"=>7,"posicion"=>"Volante","equipo_id"=>4,"created_at"=>Carbon::now()],
            ["rut"=>"21212179-3","nombre"=>"Phillipp","apellido"=>"Dobinson","numero_camiseta"=>11,"posicion"=>"Defensa","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"29753913-3","nombre"=>"Cesare","apellido"=>"Kubiak","numero_camiseta"=>24,"posicion"=>"Arquero","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"22622489-3","nombre"=>"Giuseppe","apellido"=>"Loynton","numero_camiseta"=>14,"posicion"=>"Defensa","equipo_id"=>4,"created_at"=>Carbon::now()],
            ["rut"=>"10859237-5","nombre"=>"Aguste","apellido"=>"Izkovici","numero_camiseta"=>24,"posicion"=>"Arquero","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"17087613-7","nombre"=>"Lamond","apellido"=>"Ellesworth","numero_camiseta"=>12,"posicion"=>"Volante","equipo_id"=>4,"created_at"=>Carbon::now()],
            ["rut"=>"29812753-6","nombre"=>"Ephrem","apellido"=>"Oty","numero_camiseta"=>12,"posicion"=>"Defensa","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"13925094-1","nombre"=>"Link","apellido"=>"Girardengo","numero_camiseta"=>20,"posicion"=>"Delantero","equipo_id"=>1,"created_at"=>Carbon::now()],
            ["rut"=>"19902787-6","nombre"=>"Brady","apellido"=>"Sentance","numero_camiseta"=>34,"posicion"=>"Delantero","equipo_id"=>1,"created_at"=>Carbon::now()],
            ["rut"=>"28789797-0","nombre"=>"Dougy","apellido"=>"Langthorne","numero_camiseta"=>27,"posicion"=>"Volante","equipo_id"=>6,"created_at"=>Carbon::now()],
            ["rut"=>"13685984-8","nombre"=>"Stern","apellido"=>"Luckwell","numero_camiseta"=>37,"posicion"=>"Arquero","equipo_id"=>2,"created_at"=>Carbon::now()],
            ["rut"=>"21665027-5","nombre"=>"Cale","apellido"=>"Woodvine","numero_camiseta"=>38,"posicion"=>"Volante","equipo_id"=>2,"created_at"=>Carbon::now()],
            ["rut"=>"29718663-7","nombre"=>"Tirrell","apellido"=>"Egarr","numero_camiseta"=>15,"posicion"=>"Arquero","equipo_id"=>3,"created_at"=>Carbon::now()],
            ["rut"=>"25014400-2","nombre"=>"Geoffry","apellido"=>"Soall","numero_camiseta"=>4,"posicion"=>"Delantero","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"17230381-3","nombre"=>"Jamison","apellido"=>"Kittel","numero_camiseta"=>37,"posicion"=>"Arquero","equipo_id"=>5,"created_at"=>Carbon::now()],
            ["rut"=>"16190680-1","nombre"=>"Jereme","apellido"=>"Carver","numero_camiseta"=>39,"posicion"=>"Volante","equipo_id"=>2,"created_at"=>Carbon::now()],
            ["rut"=>"25401277-1","nombre"=>"Ramon","apellido"=>"Gregersen","numero_camiseta"=>19,"posicion"=>"Defensa","equipo_id"=>7,"created_at"=>Carbon::now()],
            ["rut"=>"19759538-8","nombre"=>"Thoma","apellido"=>"Vedntyev","numero_camiseta"=>2,"posicion"=>"Delantero","equipo_id"=>2,"created_at"=>Carbon::now()],
            ["rut"=>"27136741-8","nombre"=>"Marion","apellido"=>"Swann","numero_camiseta"=>2,"posicion"=>"Defensa","equipo_id"=>1,"created_at"=>Carbon::now()],
            ["rut"=>"13281880-0","nombre"=>"Chadd","apellido"=>"Verriour","numero_camiseta"=>12,"posicion"=>"Volante","equipo_id"=>4,"created_at"=>Carbon::now()],
            ["rut"=>"22105081-2","nombre"=>"Goraud","apellido"=>"Raggett","numero_camiseta"=>39,"posicion"=>"Defensa","equipo_id"=>7,"created_at"=>Carbon::now()],
            ["rut"=>"12370774-4","nombre"=>"Goran","apellido"=>"Esson","numero_camiseta"=>1,"posicion"=>"Arquero","equipo_id"=>6,"created_at"=>Carbon::now()],
            ["rut"=>"27707305-9","nombre"=>"Lucius","apellido"=>"Franies","numero_camiseta"=>36,"posicion"=>"Volante","equipo_id"=>2,"created_at"=>Carbon::now()],
            ["rut"=>"29707637-4","nombre"=>"Aylmer","apellido"=>"Darleston","numero_camiseta"=>17,"posicion"=>"Delantero","equipo_id"=>7,"created_at"=>Carbon::now()],
        ]);
    }
}
